name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Build
        run: mvn clean package

      - name: Run tests
        run: mvn test

      - name: Run Java Server in Background
        run: |
          java -jar target/*.jar &
          sleep 10 # Give the server a few seconds to start up
